-- =====================================================================
-- GREEN MARKET — DATABASE SCHEMA & INITIALIZATION SCRIPT
-- Enforces COD Marketplace business logic, RLS isolation, and triggers.
-- =====================================================================

-- ── 1. EXTENSIONS & ENUMS ─────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pg_trgm; -- Trigram search for Phase 2

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('customer', 'seller', 'admin');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
        CREATE TYPE order_status AS ENUM ('placed', 'packed', 'to_receive', 'received', 'cancelled');
    END IF;
END $$;

-- ── 2. TABLES ────────────────────────────────────────────────────────
-- PROFILES (Linked 1:1 with auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id               UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name        TEXT NOT NULL,
    role             user_role NOT NULL DEFAULT 'customer',
    phone_number     TEXT,
    delivery_address TEXT,
    metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- PRODUCTS (Owned by a seller profile)
CREATE TABLE IF NOT EXISTS public.products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id      UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title          TEXT NOT NULL,
    description    TEXT,
    price          NUMERIC(10, 2) NOT NULL CONSTRAINT positive_price CHECK (price >= 0.00),
    stock_quantity INT NOT NULL DEFAULT 0 CONSTRAINT non_negative_stock CHECK (stock_quantity >= 0),
    image_url      TEXT,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- PRODUCT VARIATIONS (Options like sizing or bulk packaging)
CREATE TABLE IF NOT EXISTS public.product_variations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    name           TEXT NOT NULL,
    value          TEXT NOT NULL,
    price_modifier NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    stock_quantity INT NOT NULL DEFAULT 0 CONSTRAINT var_non_negative_stock CHECK (stock_quantity >= 0)
);

-- CART ITEMS (Current active baskets)
CREATE TABLE IF NOT EXISTS public.cart_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    product_id   BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    variation_id BIGINT REFERENCES public.product_variations(id) ON DELETE SET NULL,
    quantity     INT NOT NULL DEFAULT 1 CONSTRAINT positive_quantity CHECK (quantity > 0),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(customer_id, product_id, variation_id)
);

-- ORDERS (Master COD orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      UUID REFERENCES public.profiles(id) ON DELETE SET NULL NOT NULL,
    total_amount     NUMERIC(10, 2) NOT NULL CONSTRAINT positive_total CHECK (total_amount >= 0.00),
    status           order_status NOT NULL DEFAULT 'placed',
    shipping_address TEXT NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

-- ORDER ITEMS (Historical line item details with price snapshots)
CREATE TABLE IF NOT EXISTS public.order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id        BIGINT REFERENCES public.products(id) ON DELETE SET NULL NOT NULL,
    seller_id         UUID REFERENCES public.profiles(id) NOT NULL,
    variation_details TEXT,
    quantity          INT NOT NULL DEFAULT 1 CONSTRAINT item_positive_quantity CHECK (quantity > 0),
    price_at_purchase NUMERIC(10, 2) NOT NULL CONSTRAINT target_price_snapshot CHECK (price_at_purchase >= 0.00)
);

-- REVIEWS (Verified buyer comments and ratings)
CREATE TABLE IF NOT EXISTS public.reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    customer_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL NOT NULL,
    rating      INT NOT NULL CONSTRAINT star_rating_bounds CHECK (rating >= 1 AND rating <= 5),
    comment     TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(product_id, customer_id)
);

-- ── 3. TRIGGERS & FUNCTIONS ──────────────────────────────────────────
-- Function: Clamp cart items to available stock
CREATE OR REPLACE FUNCTION public.check_cart_stock_limits()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    v_available_stock INT;
BEGIN
    SELECT stock_quantity INTO v_available_stock
    FROM public.products WHERE id = NEW.product_id;

    IF NEW.quantity > v_available_stock THEN
        NEW.quantity := v_available_stock;
    END IF;

    IF NEW.quantity = 0 THEN
        RETURN NULL; -- Abort write if item out of stock
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_enforce_cart_stock ON public.cart_items;
CREATE TRIGGER tr_enforce_cart_stock
BEFORE INSERT OR UPDATE ON public.cart_items
FOR EACH ROW EXECUTE FUNCTION public.check_cart_stock_limits();

-- Function: Deduct warehouse stock on order item insertion
CREATE OR REPLACE FUNCTION public.deduct_product_stock()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public.products
    SET stock_quantity = stock_quantity - NEW.quantity
    WHERE id = NEW.product_id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_deduct_stock ON public.order_items;
CREATE TRIGGER tr_deduct_stock
AFTER INSERT ON public.order_items
FOR EACH ROW EXECUTE FUNCTION public.deduct_product_stock();

-- Function: Automatically create a profile when a new user registers
CREATE OR REPLACE FUNCTION public.handle_new_user_registration()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, role)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data ->> 'full_name', 'New User'),
        COALESCE((NEW.raw_user_meta_data ->> 'role')::user_role, 'customer')
    );
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_on_auth_user_created ON auth.users;
CREATE TRIGGER tr_on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_registration();

-- ── 4. ANALYTICS VIEWS ───────────────────────────────────────────────
CREATE OR REPLACE VIEW public.seller_analytics AS
SELECT
    oi.seller_id,
    COALESCE(SUM(oi.price_at_purchase * oi.quantity), 0.00)          AS total_earnings,
    COUNT(DISTINCT oi.order_id)                                        AS total_orders_handled,
    COUNT(DISTINCT CASE WHEN o.status = 'placed' THEN o.id END)       AS pending_orders_count,
    COUNT(DISTINCT CASE WHEN o.status = 'received' THEN o.id END)     AS completed_orders_count
FROM public.order_items oi
JOIN public.orders o ON oi.order_id = o.id
WHERE o.status != 'cancelled'
GROUP BY oi.seller_id;

-- ── 5. ROW LEVEL SECURITY (RLS) ──────────────────────────────────────
ALTER TABLE public.profiles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews           ENABLE ROW LEVEL SECURITY;

-- Helper to check the current user's role
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS user_role
LANGUAGE sql
SECURITY DEFINER
SET search_path = public AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- Grant execution to all users so they can perform RLS checks
GRANT EXECUTE ON FUNCTION public.get_user_role() TO anon, authenticated, service_role;

-- Profiles Policies
DROP POLICY IF EXISTS "profiles_select_public" ON public.profiles;
CREATE POLICY "profiles_select_public" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "profiles_update_own_or_admin" ON public.profiles;
CREATE POLICY "profiles_update_own_or_admin" ON public.profiles FOR UPDATE
USING (auth.uid() = id OR public.get_user_role() = 'admin');

-- Products Policies
DROP POLICY IF EXISTS "products_select_active_or_owner_or_admin" ON public.products;
CREATE POLICY "products_select_active_or_owner_or_admin" ON public.products FOR SELECT
USING (is_active = true OR auth.uid() = seller_id OR public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "products_insert_sellers_only" ON public.products;
CREATE POLICY "products_insert_sellers_only" ON public.products FOR INSERT
WITH CHECK (public.get_user_role() = 'seller' AND auth.uid() = seller_id);

DROP POLICY IF EXISTS "products_update_owner_or_admin" ON public.products;
CREATE POLICY "products_update_owner_or_admin" ON public.products FOR UPDATE
USING (auth.uid() = seller_id OR public.get_user_role() = 'admin');

-- Product Variations Policies
DROP POLICY IF EXISTS "variations_select_all" ON public.product_variations;
CREATE POLICY "variations_select_all" ON public.product_variations FOR SELECT USING (true);

DROP POLICY IF EXISTS "variations_write_seller_or_admin" ON public.product_variations;
CREATE POLICY "variations_write_seller_or_admin" ON public.product_variations FOR ALL
USING (
    public.get_user_role() = 'admin'
    OR EXISTS (
        SELECT 1 FROM public.products p
        WHERE p.id = product_id AND p.seller_id = auth.uid()
    )
);

-- Cart Policies
DROP POLICY IF EXISTS "cart_select_owner_only" ON public.cart_items;
CREATE POLICY "cart_select_owner_only" ON public.cart_items FOR SELECT USING (auth.uid() = customer_id);

DROP POLICY IF EXISTS "cart_all_owner_only" ON public.cart_items;
CREATE POLICY "cart_all_owner_only" ON public.cart_items FOR ALL USING (auth.uid() = customer_id);

-- Orders Policies
DROP POLICY IF EXISTS "orders_select_customer_or_seller_or_admin" ON public.orders;
CREATE POLICY "orders_select_customer_or_seller_or_admin" ON public.orders FOR SELECT
USING (
    auth.uid() = customer_id
    OR public.get_user_role() = 'admin'
    OR EXISTS (
        SELECT 1 FROM public.order_items oi
        WHERE oi.order_id = id AND oi.seller_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "orders_insert_customer_only" ON public.orders;
CREATE POLICY "orders_insert_customer_only" ON public.orders FOR INSERT
WITH CHECK (auth.uid() = customer_id);

DROP POLICY IF EXISTS "orders_update_seller_or_admin" ON public.orders;
CREATE POLICY "orders_update_seller_or_admin" ON public.orders FOR UPDATE
USING (
    public.get_user_role() = 'admin'
    OR EXISTS (
        SELECT 1 FROM public.order_items oi
        WHERE oi.order_id = id AND oi.seller_id = auth.uid()
    )
);

-- Order Items Policies
DROP POLICY IF EXISTS "order_items_select_related_parties" ON public.order_items;
CREATE POLICY "order_items_select_related_parties" ON public.order_items FOR SELECT
USING (
    seller_id = auth.uid()
    OR public.get_user_role() = 'admin'
    OR EXISTS (
        SELECT 1 FROM public.orders o
        WHERE o.id = order_id AND o.customer_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "order_items_insert_system_only" ON public.order_items;
CREATE POLICY "order_items_insert_system_only" ON public.order_items FOR INSERT
WITH CHECK (auth.uid() IS NOT NULL);

-- Reviews Policies
DROP POLICY IF EXISTS "reviews_select_public" ON public.reviews;
CREATE POLICY "reviews_select_public" ON public.reviews FOR SELECT USING (true);

DROP POLICY IF EXISTS "reviews_insert_verified_buyers_only" ON public.reviews;
CREATE POLICY "reviews_insert_verified_buyers_only" ON public.reviews FOR INSERT
WITH CHECK (
    auth.uid() = customer_id
    AND EXISTS (
        SELECT 1
        FROM public.orders o
        JOIN public.order_items oi ON oi.order_id = o.id
        WHERE o.customer_id = auth.uid()
        AND oi.product_id = product_id
        AND o.status = 'received'
    )
);

-- ── 6. PERFORMANCE INDEXES ───────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_profiles_role_id ON public.profiles(id, role);
CREATE INDEX IF NOT EXISTS idx_products_is_active_created ON public.products(is_active, created_at DESC) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_products_seller_id ON public.products(seller_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_customer_id ON public.cart_items(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer_status ON public.orders(customer_id, status);
CREATE INDEX IF NOT EXISTS idx_order_items_seller_order ON public.order_items(seller_id, order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_products_title_trgm ON public.products USING GIN (title gin_trgm_ops);

-- ── 7. SEED DATA ─────────────────────────────────────────────────────
INSERT INTO public.profiles (id, full_name, role, phone_number, delivery_address, metadata)
VALUES
    (
        '00000000-0000-0000-0000-000000000001',
        'Carlo System Admin',
        'admin',
        '+639171112233',
        'Green Market Central HQ, Bacolod City',
        '{"is_super_user": true, "department": "Platform Security"}'::jsonb
    ),
    (
        '00000000-0000-0000-0000-000000000002',
        'Juan Dela Cruz Greens',
        'seller',
        '+639184445566',
        'Bais City Agro-Hub, Negros Oriental',
        '{"shop_name": "Juan Organic Farms", "is_verified": true, "shop_rating_default": 5.0}'::jsonb
    ),
    (
        '00000000-0000-0000-0000-000000000003',
        'Maria Clara TestBuyer',
        'customer',
        '+639197778899',
        'Subdivision Alpha, Block 4, Lot 2, Talisay City',
        '{"preferred_courier_notes": "Leave at front gate if not answering"}'::jsonb
    )
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (id, seller_id, title, description, price, stock_quantity, image_url, is_active)
VALUES (
    1,
    '00000000-0000-0000-0000-000000000002',
    'Premium Native Batuan Fruit',
    'Freshly harvested native Batuan fruit — organic, zero chemical preservatives.',
    180.00,
    25,
    'https://supabase.co/storage/v1/object/public/product-thumbnails/batuan.jpg',
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.product_variations (id, product_id, name, value, price_modifier, stock_quantity)
VALUES
    (1, 1, 'Bundle Size', '500g Pack',      0.00, 15),
    (2, 1, 'Bundle Size', '1kg Jumbo Pack', 150.00, 10)
ON CONFLICT (id) DO NOTHING;
